import { expect, test } from '@playwright/test'

async function enterCleanroom(page: import('@playwright/test').Page) {
  await expect(page.getByRole('heading', { name: '환영합니다' })).toBeVisible()
  await page.getByRole('button', { name: /출입 등록 시작/ }).click()
  await expect(page.getByRole('heading', { name: '손 씻기' })).toBeVisible()
  await page.getByRole('button', { name: /세정 완료/ }).click()
  await expect(page.getByRole('heading', { name: '마스크 착용' })).toBeVisible()
  if ((page.viewportSize()?.width ?? 0) > 760) {
    const guideBox = await page.locator('.guide-dialog').boundingBox()
    const viewportWidth = page.viewportSize()?.width ?? 0
    expect(guideBox).not.toBeNull()
    expect((guideBox?.x ?? 0) + (guideBox?.width ?? 0)).toBeLessThan(viewportWidth * 0.49)
    const stageFontSize = await page.locator('.entry-progress b').first().evaluate((element) => parseFloat(getComputedStyle(element).fontSize))
    expect(stageFontSize).toBeGreaterThanOrEqual(12)
  }
  await page.getByRole('button', { name: /마스크 착용/ }).click()
  await expect(page.getByRole('heading', { name: '방진복 착용' })).toBeVisible()
  await page.getByRole('button', { name: /방진복 착용/ }).click()
  await expect(page.getByRole('heading', { name: '에어샤워 통과' })).toBeVisible()
  await page.getByRole('button', { name: /에어샤워 가동/ }).click()
  await expect(page.getByRole('heading', { name: /사건이 기다리는 공정룸/ })).toBeVisible({ timeout: 12_000 })
}

test('complete the evidence-led scenario', async ({ page }, testInfo) => {
  test.setTimeout(180_000)
  const errors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })
  await page.goto('/#photo-cd-drift')
  await expect(page.getByText('사라진 선폭의 비밀')).toBeVisible()
  await expect(page.getByText('CASE VF-PH-01')).toBeVisible()
  await expect(page.getByText('후속 Etch 투입까지 60분')).toBeVisible()
  await expect(page.locator('.station-tag')).toHaveCount(5)
  await expect(page.getByText('FAB ROOKIE', { exact: true })).toBeVisible()
  await expect(page.locator('.mission-hud')).toContainText('MISSION 01')
  await page.waitForTimeout(800)
  await page.screenshot({ path: testInfo.outputPath('first-viewport.png'), fullPage: true })

  if (testInfo.project.name === 'mobile') {
    await expect(page.locator('.workbench')).toBeVisible()
    expect(errors).toEqual([])
    return
  }

  await page.getByRole('button', { name: /Lot 보류/ }).click()
  await page.getByRole('button', { name: /판단을 기록하고/ }).click()
  await expect(page.getByRole('heading', { name: '데이터·AI 공동분석' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: '데이터·AI 공동분석' })).toBeVisible()
  await expect(page.getByText('이전 실험을 복원했어.')).toBeVisible()
  await page.getByRole('button', { name: /EVIDENCE/ }).click()
  await expect(page.getByRole('dialog', { name: 'Evidence trail' })).toContainText('판정 보류 후 분포 확인')
  await page.getByRole('button', { name: 'Evidence 닫기' }).click()
  await expect(page.getByText('DATA · AI INVESTIGATION', { exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: '내 AI 연결' })).toBeVisible()
  await expect(page.getByLabel('AI 제공사')).toHaveValue('gemini')
  await expect(page.getByLabel('개인 API 키')).toHaveAttribute('type', 'password')
  await expect(page.getByLabel('개인 API 키')).toBeEnabled()
  await expect(page.getByText('HTTPS 연결 필요')).toHaveCount(0)
  await expect(page.getByRole('button', { name: '1. 연결 확인' })).toBeDisabled()
  await expect(page.getByRole('button', { name: '2. 질문 보내기' })).toBeDisabled()
  await expect(page.locator('.question-strategy > ol > li')).toHaveCount(5)
  await expect(page.locator('.keyword-library button')).toHaveCount(6)
  await expect(page.getByText('용어·데이터 이해', { exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: '선택 키워드로 질문 초안 만들기' }).click()
  await expect(page.getByLabel('AI에게 물어볼 다음 질문')).toHaveValue(/\[핵심 키워드\] CD, Dose/)
  await expect(page.getByText(/전송 준비 · 포함 키워드: CD, Dose/)).toBeVisible()
  const datasetDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: '합성 데이터 CSV 다운로드' }).click()
  expect((await datasetDownload).suggestedFilename()).toContain('virtual-fab-photo-cd-drift')
  await expect(page.getByRole('button', { name: '개인 키 없이 외부 AI용 질문 복사' })).toBeVisible()
  const manualAnswer = '가설 1은 Dose 변화, 가설 2는 Focus 변화, 가설 3은 측정 편향입니다. 합성 CSV의 CENTER·EDGE와 Tool·Lot 분포를 대조해 반증합니다.'
  for (let turn = 1; turn <= 8; turn += 1) {
    await page.getByLabel('외부 AI 분석 답변 붙여넣기').fill(`${manualAnswer} 현재는 ${turn}회차 분석입니다.`)
    await page.getByRole('button', { name: '현재 질문·답변을 문답 기록에 추가' }).click()
  }
  await expect(page.getByText('심층 분석 완료 조건 충족')).toBeVisible()
  await expect(page.getByText('8/8 필수 · 7회 추가 사용 가능')).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('external-ai-stage.png'), fullPage: true })
  await page.getByRole('button', { name: '분포·품질 근거로 판단' }).click()
  await page.getByRole('button', { name: /데이터·AI 문답·내 판단을 저장하고/ }).click()
  await expect(page.getByText('SCREENING DOE', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /EVIDENCE/ }).click()
  await page.getByText('데이터 다운로드 · AI 문답 8회').click()
  await expect(page.getByRole('dialog', { name: 'Evidence trail' })).toContainText('[핵심 키워드] CD, Dose')
  await expect(page.getByRole('dialog', { name: 'Evidence trail' })).toContainText('KEYWORDS · CD · Dose')
  await expect(page.getByRole('dialog', { name: 'Evidence trail' })).toContainText('가설 1은 Dose 변화')
  await page.getByRole('button', { name: 'Evidence 닫기' }).click()
  await page.getByRole('button', { name: /대조군.*Screening/ }).click()
  await page.getByRole('button', { name: /판단을 기록하고/ }).click()
  await expect(page.getByText('ANALYSIS TOOL BAY', { exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('analysis-stage.png'), fullPage: true })
  await page.getByRole('button', { name: /이 분석 조합/ }).click()
  await page.getByRole('button', { name: /판단을 기록하고/ }).click()
  await expect(page.getByText('HOLDOUT GATE', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /한정 적용/ }).click()
  await page.getByRole('button', { name: /판단을 기록하고/ }).click()
  await expect(page.getByText('시나리오 해결 · 입력 증거 기준')).toBeVisible()
  await page.getByLabel('내 판단·배운 점·한계').fill('평균값만 보지 않고 위치별 분포와 대안 가설을 확인한 뒤 최소 분석으로 검증하는 접근이 중요하다고 판단했다.')
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: /HTML 면접 PT 슬라이드/ }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe('virtual-fab-interview-slides.html')
  await page.screenshot({ path: testInfo.outputPath('complete.png'), fullPage: true })
  expect(errors).toEqual([])
})

test('open a new dry etch case from the module home', async ({ page }) => {
  await page.goto('/')
  await page.screenshot({ path: test.info().outputPath('cleanroom-entry.png'), fullPage: true })
  await enterCleanroom(page)
  await page.screenshot({ path: test.info().outputPath('process-hall.png'), fullPage: true })
  await expect(page.locator('.module-card')).toHaveCount(6)
  await page.getByRole('button', { name: 'DRY ETCH 기울어진 Sidewall 시나리오 시작' }).click()
  await expect(page.getByText('기울어진 Sidewall')).toBeVisible()
  await expect(page.getByText('CASE VF-DE-02')).toBeVisible()
  await expect(page.getByText('119.8 nm')).toBeVisible()
  await expect(page.getByRole('button', { name: /Profile·위치 분포부터 확인/ })).toBeVisible()
})

test('continue personal AI dialogue inside an automatic response popup', async ({ page }) => {
  const mockResponse = '가설 1은 챔버 위치 편차, 가설 2는 RF 조건 변화, 가설 3은 측정 편향이다. 위치별 분포와 대조군으로 각각 반증한다.'
  await page.route('**/api/sessions/*/llm/check', (route) => route.fulfill({
    contentType: 'application/json',
    body: JSON.stringify({ status: 'connected', provider: 'gemini', provider_label: 'Google Gemini', model: 'gemini-3.5-flash' }),
  }))
  await page.route('**/api/sessions/*/llm/generate', (route) => route.fulfill({
    contentType: 'application/json',
    body: JSON.stringify({ provider: 'gemini', provider_label: 'Google Gemini', model: 'gemini-3.5-flash', response: mockResponse, usage: { prompt_tokens: 100, completion_tokens: 80, thought_tokens: 45, total_tokens: 225 }, finish_reason: 'STOP', retry_count: 0 }),
  }))
  await page.goto('/#dry-etch-profile')
  await page.getByRole('button', { name: /Lot 보류/ }).click()
  await page.getByRole('button', { name: /판단을 기록하고/ }).click()
  await page.getByLabel('개인 API 키').fill('test-key-with-more-than-20-characters')
  await page.getByRole('button', { name: '1. 연결 확인' }).click()
  await expect(page.getByRole('button', { name: '2. 질문 보내기' })).toBeEnabled()
  await page.getByRole('button', { name: '2. 질문 보내기' }).click()
  const chat = page.getByRole('dialog', { name: 'AI와 공정 문제 좁히기' })
  await expect(chat).toBeVisible()
  await expect(chat).toContainText(mockResponse)
  await expect(chat).toContainText('응답 80 · 사고 45 · 전체 225 tokens')
  await expect(chat).toContainText('1/15회')
  const followUp = chat.getByLabel('다음 질문')
  await expect(followUp).toBeFocused()
  await followUp.fill('Sidewall angle 가설 중 RF bias와 위치 편차를 구분할 최소 반증 데이터는 무엇이야?')
  await chat.getByRole('button', { name: '후속 질문 보내기' }).click()
  await expect(chat).toContainText('2/15회')
  await expect(chat.locator('.chat-answer')).toHaveCount(2)
  await chat.getByRole('button', { name: 'AI 대화창 닫기' }).click()
  const responseField = page.getByLabel('외부 AI 분석 답변 붙여넣기')
  await expect(responseField).toHaveValue(mockResponse)
  await expect(page.getByText(/응답이 자동 입력됐어/)).toBeVisible()
  await responseField.fill(`${mockResponse} 사람이 수정한 문장.`)
  await expect(responseField).toHaveValue(/사람이 수정한 문장/)
})
