import { expect, test } from '@playwright/test'

async function enterCleanroom(page: import('@playwright/test').Page) {
  await expect(page.getByRole('heading', { name: '가상 팹 접속' })).toBeVisible()
  await page.getByRole('button', { name: /출입 등록 시작/ }).click()
  await expect(page.getByRole('heading', { name: '손 씻기' })).toBeVisible()
  await page.getByRole('button', { name: /세정 완료/ }).click()
  await expect(page.getByRole('heading', { name: '마스크 착용' })).toBeVisible()
  await page.getByRole('button', { name: /마스크 착용/ }).click()
  await expect(page.getByRole('heading', { name: '방진복 착용' })).toBeVisible()
  await page.getByRole('button', { name: /방진복 착용/ }).click()
  await expect(page.getByRole('heading', { name: '에어샤워 통과' })).toBeVisible()
  await page.getByRole('button', { name: /에어샤워 가동/ }).click()
  await expect(page.getByRole('heading', { name: /사건이 기다리는 공정룸/ })).toBeVisible()
}

test('complete the evidence-led scenario', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })
  await page.goto('/#photo-cd-drift')
  await expect(page.getByText('사라진 선폭의 비밀')).toBeVisible()
  await expect(page.getByText('CASE VF-PH-01')).toBeVisible()
  await expect(page.getByText('후속 Etch 투입까지 60분')).toBeVisible()
  await expect(page.locator('.station-tag')).toHaveCount(6)
  await expect(page.getByText('FAB ROOKIE', { exact: true })).toBeVisible()
  await expect(page.locator('.mission-hud')).toContainText('MISSION 01')
  await page.waitForTimeout(800)
  await page.screenshot({ path: testInfo.outputPath('first-viewport.png'), fullPage: true })

  if (testInfo.project.name === 'mobile') {
    await expect(page.locator('.workbench')).toBeVisible()
    expect(errors).toEqual([])
    return
  }

  await page.getByRole('button', { name: /Lot 보류/ }).click()
  await page.getByRole('button', { name: /판단을 기록하고/ }).click()
  await expect(page.getByRole('heading', { name: 'LLM Coach' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'LLM Coach' })).toBeVisible()
  await expect(page.getByText('이전 실험을 복원했어.')).toBeVisible()
  await page.getByRole('button', { name: /EVIDENCE/ }).click()
  await expect(page.getByRole('dialog', { name: 'Evidence trail' })).toContainText('판정 보류 후 분포 확인')
  await page.getByRole('button', { name: 'Evidence 닫기' }).click()
  await expect(page.getByText('EXTERNAL AI WORKBENCH', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'DeepSeek API로 분석' })).toBeVisible()
  await expect(page.getByRole('button', { name: '다른 AI용 프롬프트 복사' })).toBeVisible()
  await page.getByLabel('외부 AI 분석 답변 붙여넣기').fill('가설 1은 Dose 변화, 가설 2는 현상 균일도, 가설 3은 측정 편향입니다. 각각을 대조군과 위치별 분포로 반증합니다.')
  await page.screenshot({ path: testInfo.outputPath('external-ai-stage.png'), fullPage: true })
  await page.getByRole('button', { name: '수정 채택' }).click()
  await page.getByRole('button', { name: /질문·답변·판단을 저장하고/ }).click()
  await expect(page.getByText('DISTRIBUTION MAP', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /EVIDENCE/ }).click()
  await page.getByText('Gemini 질문·답변').click()
  await expect(page.getByRole('dialog', { name: 'Evidence trail' })).toContainText('경쟁 가설 3개와 각 가설을 반증할')
  await expect(page.getByRole('dialog', { name: 'Evidence trail' })).toContainText('가설 1은 Dose 변화')
  await page.getByRole('button', { name: 'Evidence 닫기' }).click()
  await page.getByRole('button', { name: '분포로 판단' }).click()
  await page.getByRole('button', { name: /판단을 기록하고/ }).click()
  await expect(page.getByText('SCREENING DOE', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /대조군.*Screening/ }).click()
  await page.getByRole('button', { name: /판단을 기록하고/ }).click()
  await expect(page.getByText('ANALYSIS TOOL BAY', { exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('analysis-stage.png'), fullPage: true })
  await page.getByRole('button', { name: /이 분석 조합/ }).click()
  await page.getByRole('button', { name: /판단을 기록하고/ }).click()
  await expect(page.getByText('HOLDOUT GATE', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /한정 적용/ }).click()
  await page.getByRole('button', { name: /판단을 기록하고/ }).click()
  await expect(page.getByText('시나리오 해결 · 입력 증거 기준')).toBeVisible()
  await page.getByLabel('내 판단·배운 점·한계').fill('평균값만 보지 않고 위치별 분포와 대안 가설을 확인한 뒤 최소 분석으로 검증하는 접근이 중요하다고 판단했다.')
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: /Base64 HTML 면접 슬라이드/ }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe('virtual-fab-interview-slides.html')
  await page.screenshot({ path: testInfo.outputPath('complete.png'), fullPage: true })
  expect(errors).toEqual([])
})

test('open a new dry etch case from the module home', async ({ page }) => {
  await page.goto('/')
  await page.screenshot({ path: test.info().outputPath('cleanroom-entry.png'), fullPage: true })
  await enterCleanroom(page)
  await page.screenshot({ path: test.info().outputPath('process-hall.png'), fullPage: true })
  await expect(page.locator('.module-card')).toHaveCount(6)
  await page.getByRole('button', { name: 'DRY ETCH 기울어진 Sidewall 시나리오 시작' }).click()
  await expect(page.getByText('기울어진 Sidewall')).toBeVisible()
  await expect(page.getByText('CASE VF-DE-02')).toBeVisible()
  await expect(page.getByText('119.8 nm')).toBeVisible()
  await expect(page.getByRole('button', { name: /Profile·위치 분포부터 확인/ })).toBeVisible()
})
